---
title: "yarrr_explore"
author: "Chelsey"
date: "5/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r attach_yarrr}
library(yarrr)
pirateplot(formula = weight ~ Time, 
           data = ChickWeight,
           pal = "xmen")
```
```{r attach_tidy}
library(tidyverse)
```
```{r explore_data}
head(pirates)
names(pirates)
view(pirates)
```
```{r mean}
#What is mean pirate age
mean(pirates$age)
```
```{r summary}
summary(pirates)
```
```{r max}
#Who is the tallest pirate
max(pirates$height)
```
```{r sex}

 pirate_sex <- table(pirates$sex)
pirate_sex_tidy <- pirates %>%
  group_by(sex)
```
```{r age sex}
aggregate(formula= age~sex, data=pirates, FUN=mean)
```
```{r age_sex_tidy}
pirate_age_sex <- pirate_sex_tidy %>%
  summarise(mean=mean(age))
library(kableExtra)
pirate_age_sex%>%
  kable()%>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```
```{r plotting}
ggplot(data=pirates, aes(x=height, y=weight))+geom_point(color="orchid",pch=18)+theme_light()+labs(x="Height in", y="Weight lbs", title="Pirate Height and Weight")

model <- lm(formula=height~weight, data=pirates)


```
```{r regression}
ggplot(data=pirates, aes(x=height, y=weight))+geom_point(color="skyblue", pch=18)+theme_light()+labs(x="Height in", y="Weight lbs", title="Pirate Height and Weight")+geom_smooth(method='lm',formula=y~x, color="yellow")
```
```{r pirate plot}
pirateplot(formula = age ~ sword.type, 
           data = pirates,
           main = "Pirateplot of ages by favorite sword")
```
```{r pirate plot 2}
pirateplot(formula = height ~ sex,               # Plot weight as a function of sex
           data = pirates,                       
           main = "Pirateplot of height by sex",
           pal = "pony",                         # Use the info color palette
           theme = 3)                            # Use theme 3

```
```{r pony pal}
# Show me the pony palette!
piratepal(palette = "pony",
          plot.result = TRUE,   # Plot the result
          trans = .1)           # Slightly transparent
```