---
title: "Indexing"
author: "Chelsey"
date: "6/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# **Indexing**
```{r boat data}
# Boat sale. Creating the data vectors
boat.names <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
boat.colors <- c("black", "green", "pink", "blue", "blue", 
                "green", "green", "yellow", "black", "black")
boat.ages <- c(143, 53, 356, 23, 647, 24, 532, 43, 66, 86)
boat.prices <- c(53, 87, 54, 66, 264, 32, 532, 58, 99, 132)
boat.costs <- c(52, 80, 20, 100, 189, 12, 520, 68, 80, 100)
```
```{r idexing boats}
# What was the price of the first boat?
boat.prices[1]
## [1] 53

# What were the ages of the first 5 boats?
boat.ages[1:5]
## [1] 143  53 356  23 647

# What were the names of the black boats?
boat.names[boat.colors == "black"]
## [1] "a" "i" "j"

# What were the prices of either green or yellow boats?
boat.prices[boat.colors == "green" | boat.colors == "yellow"]
## [1]  87  32 532  58

# Change the price of boat "s" to 100
boat.prices[boat.names == "s"] <- 100

# What was the median price of black boats less than 100 years old?
median(boat.prices[boat.colors == "black" & boat.ages < 100])
## [1] 116

# How many pink boats were there?
sum(boat.colors == "pink")
## [1] 1

# What percent of boats were older than 100 years old?
mean(boat.ages < 100)
## [1] 0.6
```
## **Numerical Indexing**
```{r numerical indexing}
boat.names[1]

boat.colors [1:5]

boat.ages[seq(1,5,by=2)]

boat.ages[c(1,1,1)]

index<- 3:5

boat.names[index]

```
## **Logical Indexing**
```{r logical idexing}

a <- c(1, 2, 3, 4, 5)
a[c(TRUE, FALSE, TRUE, FALSE, TRUE)]

boat.ages >100

boat.ages == 23

boat.names == "c"

#comparing vectors 

boat.prices > boat.costs

boat.prices < boat.costs

boat.prices [boat.ages >100]

boat.prices >200 | boat.prices <100 

boat.names [boat.prices >200 | boat.prices <100 ]

boat.names [boat.colors == "black" | boat.prices >100]

(boat.colors == "black" | boat.colors == "brown") & boat.prices <100

boat.names [(boat.colors == "black" | boat.colors == "brown") & boat.prices <100]

#multiple OR arguments with %n%

x <- c("a", "t", "a", "b", "z")

x %in% c("a","b","c","d")
```
```{r counts and percentages with logical indexing}

x <- c(1, 2, 3, -5, -5, -5, -5, -5)

x > 0

sum (x >0)

mean (x>0)

duplicated (x)

```
```{r changing values}

a <- rep(1, 10)

a[1:5] <- 9

a

a[6:10] <- 0
a

x <- c(5, -5, 7, 4, 11, 5, -2)

x [x<1] <- 1

x

x [x>10] <- 10

x

#happy survey example 

happy <- c(1, 4, 2, 999, 2, 3, -2, 3, 2, 999)

invalid <- (happy %in% 1:5) == FALSE
invalid

happy [invalid] <- NA

happy

happy[(happy %in% 1:5) == FALSE] <- NA

happy

mean (happy, na.rm=TRUE)

```
# ** Test your might: Movie Data** 
```{r test your might}

movie.name <- c( "whatever works", "it follows", "love and mercy", "the goonies", "jiro dreams of sushi", "there will be blood", "moon", "spice world", "serenity", "finding vivan maier")
movie.year <- c(2009, 2015, 2015, 1985, 2012, 2007,2009, 1998, 2005, 2014)
move.boxoffice <- c(35, 15, 15, 62, 3, 10, 321, 79, 39, 1.5)
movie.genre <- c("comedy", "horror", "drama", "adventure", "documentary", "drama", "science fiction", "comedy", "science fiction", "documentary")
movie.time <- c(92, 97, 120, 90, 81, 158, 97, -84, 119, 84)
movie.rating <- c("PG13", "r", "r", "pg", "g", "r", "r", "pg13", "unrated")

#name of the 10th movie 

movie.name [10]

#genre of the first four movies 

movie.genre [1:4]

#change spice world to naked gun 

movie.name [movie.name == "spice world"] <- "naked gun"

movie.name

#movies beofre the year 1990

movie.name[movie.year< 1990]

#how many movies were dramas

sum(movie.genre == "drama")

#what percentage of movies were comedies 

mean(movie.genre== "comedy")

#replace time that is invalid with NA 

movie.time [movie.time <0] <- NA

movie.time

#Average movie time 

mean(movie.time, na.rm=TRUE)

#What are the names of the comedy movies 

movie.name[movie.genre=="comedy"]

#WHat are the comedy movie box office totals 

move.boxoffice [ movie.genre == "comedy"]

#Movies that made less than 50 Mill and were comedies 

movie.name [move.boxoffice<50 & movie.genre == "comedy"]

#What was the median box office revenue for movies rated G or PG

median(move.boxoffice[movie.rating== "g"| movie.rating == "pg"])

#Percentage of movies that were rated R or comedies 

mean(movie.rating== "r" | movie.genre == "comedy")
```