---
title: "Loops"
author: "Chelsey"
date: "8/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ** Intro to loops**
```{r intro loops}

# Print the integers from 1 to 10
for(numbers  in 1:10) {
  
  print(numbers)
  
}

#Loop to sum integers from 1 to 100

current.sum <- 0 # The starting value of current.sum

for(i in 1:100) {

 current.sum <- current.sum + i # Add i to current.sum

}

current.sum

```
# ** Plot Loops**
```{r plot loops}

library(yarrr)

head(examscores)

par(mfrow = c(2, 2))  # Set up a 2 x 2 plotting space

# Create the loop.vector (all the columns)
loop.vector <- 1:4

for (i in loop.vector) { # Loop over loop.vector

   # store data in column.integer as x
  x <- examscores[,i]
  
  # Plot histogram of x
  hist(x,
       main = paste("Question", i),
       xlab = "Scores",
       xlim = c(0, 100))
}

head(examscores)

```
# ** Container Object Updates**
```{r container objects}

# Create a container object of 4 NA values
failure.percent <- rep(NA, 4)

for(scores in 1:4) { # Loop over columns 1 through 4

  # Get the scores for the ith column (doesn't have to be i?)
  x <- examscores[,scores] 
  
  # Calculate the percent of failures
  failures.i <- mean(x < 50)  
  
   # Assign result to the ith value of failure.percent
  failure.percent[scores] <- failures.i 

}

failure.percent



```
# **Design matrix**

```{r design matrix}

design.matrix <- expand.grid("college" = c("JSSFP", "CCCC"), # college factor
                             "sex" = c("male", "female"), # sex factor
                             "median.age" = NA, # NA columns for our future calculations
                             "mean.age" = NA, #...
                             "sd.age" = NA, #...
                             stringsAsFactors = FALSE)

design.matrix

for(row.i in 1:nrow(design.matrix)) {

# Get factor values for current row
  college.i <- design.matrix$college[row.i]
  sex.i <- design.matrix$sex[row.i]

# Subset pirates with current factor values
  data.temp <- subset(pirates, 
                      college == college.i & sex == sex.i)

# Calculate statistics
  median.i <- median(data.temp$age)
  mean.i <- mean(data.temp$age)
  sd.i <- sd(data.temp$age)

# Assign statistics to row.i of design.matrix
  design.matrix$median.age[row.i] <- median.i
  design.matrix$mean.age[row.i] <- mean.i
  design.matrix$sd.age[row.i] <- sd.i

}

design.matrix

```