---
title: "Scalar_Vector"
author: "Chelsey"
date: "5/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Vectors**
```{r numeric vectors}
#create an object called a spanning 1-5

a<- c(1,2,3,4,5)
#View(a)or print a

#add vector b 6-10

b<- c(6,7,8,9,10)

x<- c(a,b)

x

```
**Test your might**
```{r test your might 1a}
c(1,2,3,4,5,6,7,8,9,10)
```
```{r test your might 1b}
 1:10
```
```{r test your might 1c}
seq(from=1, to=10)
```
```{r test your might 2a}
 
c(2.1,4.1,6.1,8.1)
```

```{r test your might 2b}
seq(from=2.1, to=8.1, by=2)
```
```{r test your might 3a}
c (0,5,10,15)
```
```{r test your might 3b}
seq(from=0, to=15, by=5)
```
```{r test your might 3c}
seq(from=0, to=15, length.out=4)
```
```{r test your might 4}
c( seq(from=101,to=103), 
       seq( from=200, to=210, by=5),
   seq(from=1000, to=1200, by=100))
```
```{r test your might 5}
swords <- rep(c("scimitar", rep("broadsword",4), rep("cutlass",5)), times =100) 
          head(swords)
```
```{r test your might 6}
rep(seq(from=1, to=5),times=10)
```
```{r test your might 7}
c(rep(1,times=10), rep(2, times=10), rep(3, times=10), rep(4, times=10, rep (5, times=10)))
```
```{r test your might 8}
rnorm(n=50, mean=20, sd=2)
```
```{r test your might 9}
runif(n=25, min=-100,max=-50)
```
